development:
  adapter: postgresql
  encoding: unicode
  database: agenda2_development
  pool: 5
  username: agenda2
  password: agenda2
  host: 127.0.0.1

test:
  adapter: postgresql
  encoding: unicode
  database: agenda2_test
  pool: 5
  username: agenda2
  password: agenda2
  host: 127.0.0.1

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
